#!/bin/sh
# shell script that interactively deletes a file

echo '======================================================'
echo "\$rmi-ss "
echo "Please give a file name"
a=0
while test $a -eq 0
 do
  echo -n "\$rmi-ss "; read file
  if test -d $file
   then
    echo $file "is a directory"
   else
    if test ! -f $file
     then
      echo "No such file:" $file
     else
      echo "Do you want to delete the file" $file "(y/n)?"
      read response
      if test $response = "y"
       then
        rm $file
        echo $file "removed upon your request"
        echo "\$"
        echo ""
        echo '===================================================='
  	a=1
       else
        echo $file "not removed"
      fi
    fi
  fi
done 
